storage:
  type: 'mongo' # valid values: json, mongo
  credentials:
    host: 'localhost'
    port: 27017
    database: 'polls'
    username: 'user'
    password: 'admin'
sound:
  click: 'CLICK 1 1'
  info: 'NOTE_PLING 1 1'
  warning: 'NOTE_PLING 1 0.75'
  error: 'NOTE_PLING 0.5'